import type { TabooCard } from "./types";

export const ALL_CARDS: TabooCard[] = [
  // ── Food & Drinks ──────────────────────────────────────────────────────────
  { word: "Pizza", tabooWords: ["Cheese", "Slice", "Italy", "Dough", "Delivery"] },
  { word: "Sushi", tabooWords: ["Japan", "Fish", "Rice", "Roll", "Raw"] },
  { word: "Hamburger", tabooWords: ["Beef", "Bun", "Patty", "Grill", "Fast"] },
  { word: "Coffee", tabooWords: ["Cup", "Caffeine", "Morning", "Brew", "Bean"] },
  { word: "Ice Cream", tabooWords: ["Cone", "Scoop", "Cold", "Milk", "Flavor"] },
  { word: "Chocolate", tabooWords: ["Cocoa", "Sweet", "Brown", "Bar", "Candy"] },
  { word: "Spaghetti", tabooWords: ["Pasta", "Sauce", "Noodle", "Italian", "Meatball"] },
  { word: "Avocado", tabooWords: ["Toast", "Green", "Guacamole", "Fruit", "Healthy"] },
  { word: "Bacon", tabooWords: ["Pork", "Crispy", "Breakfast", "Fat", "Strip"] },
  { word: "Birthday Cake", tabooWords: ["Candles", "Frosting", "Party", "Sugar", "Bake"] },
  { word: "Sandwich", tabooWords: ["Bread", "Lunch", "Fill", "Deli", "Sub"] },
  { word: "Tacos", tabooWords: ["Mexican", "Shell", "Beef", "Salsa", "Fold"] },
  { word: "Popcorn", tabooWords: ["Movie", "Kernel", "Butter", "Crunch", "Cinema"] },
  { word: "Pancakes", tabooWords: ["Syrup", "Breakfast", "Flat", "Batter", "Stack"] },
  { word: "Hot Dog", tabooWords: ["Sausage", "Bun", "Mustard", "Grill", "Ballpark"] },
  { word: "Soda", tabooWords: ["Fizzy", "Can", "Sugar", "Drink", "Carbonated"] },
  { word: "Steak", tabooWords: ["Beef", "Grill", "Rare", "Cut", "Meat"] },
  { word: "Salad", tabooWords: ["Lettuce", "Healthy", "Vegetable", "Bowl", "Dressing"] },
  { word: "Donut", tabooWords: ["Hole", "Sugar", "Ring", "Glaze", "Bakery"] },
  { word: "Cookie", tabooWords: ["Bake", "Sweet", "Chip", "Dough", "Jar"] },
  { word: "Smoothie", tabooWords: ["Blend", "Fruit", "Healthy", "Drink", "Straw"] },
  { word: "Waffles", tabooWords: ["Iron", "Syrup", "Grid", "Breakfast", "Batter"] },
  { word: "Potato Chips", tabooWords: ["Crispy", "Bag", "Salty", "Snack", "Potato"] },
  { word: "Ramen", tabooWords: ["Japan", "Noodle", "Broth", "Bowl", "Soup"] },
  { word: "Burrito", tabooWords: ["Wrap", "Mexican", "Bean", "Rice", "Foil"] },
  { word: "Peanut Butter", tabooWords: ["Jelly", "Spread", "Jar", "Nut", "Sandwich"] },
  { word: "Strawberry", tabooWords: ["Red", "Berry", "Fruit", "Jam", "Sweet"] },
  { word: "Lemonade", tabooWords: ["Lemon", "Sugar", "Summer", "Yellow", "Drink"] },
  { word: "Cereal", tabooWords: ["Bowl", "Milk", "Morning", "Crunch", "Breakfast"] },
  { word: "Lasagna", tabooWords: ["Layer", "Italy", "Pasta", "Bake", "Cheese"] },
  { word: "Mango", tabooWords: ["Tropical", "Yellow", "Fruit", "Juice", "India"] },
  { word: "Grilled Cheese", tabooWords: ["Butter", "Sandwich", "Melt", "Bread", "Yellow"] },
  { word: "Pumpkin Pie", tabooWords: ["Thanksgiving", "Spice", "Orange", "Crust", "Dessert"] },
  { word: "Sour Cream", tabooWords: ["Dip", "Dairy", "White", "Taco", "Cold"] },
  { word: "Nachos", tabooWords: ["Cheese", "Chip", "Salsa", "Mexican", "Crunch"] },

  // ── Technology & Social Media ───────────────────────────────────────────────
  { word: "Twitter", tabooWords: ["Tweet", "Elon", "Social", "Follow", "Post"] },
  { word: "Instagram", tabooWords: ["Photo", "Filter", "Story", "Selfie", "Follow"] },
  { word: "Netflix", tabooWords: ["Stream", "Show", "Binge", "Movie", "Subscribe"] },
  { word: "Google", tabooWords: ["Search", "Engine", "Map", "Browser", "Internet"] },
  { word: "iPhone", tabooWords: ["Apple", "Screen", "App", "Camera", "Touch"] },
  { word: "YouTube", tabooWords: ["Video", "Watch", "Channel", "Subscribe", "Stream"] },
  { word: "Amazon", tabooWords: ["Order", "Ship", "Prime", "Package", "Store"] },
  { word: "Facebook", tabooWords: ["Like", "Friend", "Post", "Profile", "Social"] },
  { word: "TikTok", tabooWords: ["Video", "Dance", "Short", "Trend", "Viral"] },
  { word: "Email", tabooWords: ["Send", "Inbox", "Subject", "Mail", "Attach"] },
  { word: "Laptop", tabooWords: ["Screen", "Keyboard", "Portable", "Computer", "Battery"] },
  { word: "Headphones", tabooWords: ["Music", "Ear", "Listen", "Wire", "Sound"] },
  { word: "Wi-Fi", tabooWords: ["Internet", "Connect", "Signal", "Router", "Wireless"] },
  { word: "Bluetooth", tabooWords: ["Wireless", "Connect", "Pair", "Ear", "Speaker"] },
  { word: "Selfie", tabooWords: ["Photo", "Front", "Camera", "Pose", "Mirror"] },
  { word: "Podcast", tabooWords: ["Listen", "Episode", "Audio", "Show", "Subscribe"] },
  { word: "Spotify", tabooWords: ["Music", "Stream", "Playlist", "Song", "Headphone"] },
  { word: "ChatGPT", tabooWords: ["AI", "Chat", "Robot", "Answer", "Type"] },
  { word: "Cryptocurrency", tabooWords: ["Bitcoin", "Digital", "Currency", "Invest", "Block"] },
  { word: "Emoji", tabooWords: ["Face", "Symbol", "Text", "Keyboard", "Yellow"] },
  { word: "Hashtag", tabooWords: ["Symbol", "Social", "Trend", "Tag", "Follow"] },
  { word: "Password", tabooWords: ["Security", "Login", "Secret", "Code", "Access"] },
  { word: "Download", tabooWords: ["File", "Click", "Wait", "Internet", "Save"] },
  { word: "Swipe", tabooWords: ["Phone", "Right", "Left", "Match", "Screen"] },
  { word: "Charger", tabooWords: ["Battery", "Cable", "Plug", "Power", "Wall"] },

  // ── Movies & TV Shows ───────────────────────────────────────────────────────
  { word: "Harry Potter", tabooWords: ["Magic", "Wand", "School", "Wizard", "Hogwarts"] },
  { word: "Star Wars", tabooWords: ["Jedi", "Space", "Force", "Galaxy", "Empire"] },
  { word: "The Avengers", tabooWords: ["Marvel", "Hero", "Superhero", "Team", "Fight"] },
  { word: "Titanic", tabooWords: ["Ship", "Sink", "Ocean", "Love", "Jack"] },
  { word: "The Lion King", tabooWords: ["Africa", "Lion", "King", "Jungle", "Disney"] },
  { word: "Game of Thrones", tabooWords: ["Dragon", "Throne", "Kingdom", "Fantasy", "Winter"] },
  { word: "Stranger Things", tabooWords: ["Monster", "Kids", "80s", "Lab", "Upside"] },
  { word: "Breaking Bad", tabooWords: ["Drug", "Cook", "Chemistry", "Crime", "Desert"] },
  { word: "The Office", tabooWords: ["Work", "Paper", "Boss", "Comedy", "Desk"] },
  { word: "Friends", tabooWords: ["New York", "Apartment", "Six", "Coffee", "Sitcom"] },
  { word: "Jurassic Park", tabooWords: ["Dinosaur", "Island", "Clone", "Park", "Run"] },
  { word: "Spider-Man", tabooWords: ["Web", "Hero", "Mask", "Swing", "Bite"] },
  { word: "Frozen", tabooWords: ["Ice", "Queen", "Snow", "Sister", "Disney"] },
  { word: "The Matrix", tabooWords: ["Pill", "Simulation", "Code", "Agent", "Reality"] },
  { word: "Shrek", tabooWords: ["Ogre", "Swamp", "Princess", "Fairy", "Green"] },
  { word: "Inception", tabooWords: ["Dream", "Spin", "Layer", "Sleep", "Mind"] },
  { word: "Toy Story", tabooWords: ["Toy", "Cowboy", "Buzz", "Andy", "Pixar"] },
  { word: "Moana", tabooWords: ["Ocean", "Island", "Hawaii", "Disney", "Wave"] },
  { word: "Joker", tabooWords: ["Clown", "Villain", "Laugh", "Batman", "Crime"] },
  { word: "Squid Game", tabooWords: ["Korea", "Money", "Game", "Death", "Green"] },
  { word: "Avatar", tabooWords: ["Blue", "Alien", "Planet", "Tree", "Nature"] },
  { word: "The Simpsons", tabooWords: ["Yellow", "Springfield", "Donut", "Family", "Cartoon"] },
  { word: "Cluedo", tabooWords: ["Mansion", "Murder", "Colonel", "Board", "Suspect"] },
  { word: "Black Panther", tabooWords: ["Africa", "Vibranium", "King", "Marvel", "Cat"] },
  { word: "Grease", tabooWords: ["Musical", "Leather", "Sandy", "Dance", "1950s"] },

  // ── Sports & Activities ─────────────────────────────────────────────────────
  { word: "Soccer", tabooWords: ["Kick", "Goal", "Field", "Team", "Ball"] },
  { word: "Basketball", tabooWords: ["Hoop", "Dunk", "Court", "Ball", "NBA"] },
  { word: "American Football", tabooWords: ["Touchdown", "Field", "Quarterback", "Helmet", "Super"] },
  { word: "Tennis", tabooWords: ["Racket", "Court", "Net", "Ball", "Wimbledon"] },
  { word: "Swimming", tabooWords: ["Pool", "Water", "Lap", "Stroke", "Dive"] },
  { word: "Golf", tabooWords: ["Club", "Course", "Hole", "Green", "Ball"] },
  { word: "Baseball", tabooWords: ["Bat", "Pitch", "Home", "Glove", "Diamond"] },
  { word: "Volleyball", tabooWords: ["Net", "Spike", "Beach", "Ball", "Team"] },
  { word: "Marathon", tabooWords: ["Run", "Mile", "Endure", "Road", "Train"] },
  { word: "Gymnastics", tabooWords: ["Flip", "Vault", "Floor", "Ribbon", "Olympics"] },
  { word: "Boxing", tabooWords: ["Punch", "Ring", "Glove", "Round", "Fight"] },
  { word: "Skateboarding", tabooWords: ["Board", "Trick", "Ramp", "Wheels", "Street"] },
  { word: "Yoga", tabooWords: ["Pose", "Stretch", "Mat", "Balance", "Breathe"] },
  { word: "Hiking", tabooWords: ["Trail", "Mountain", "Boot", "Nature", "Walk"] },
  { word: "Surfing", tabooWords: ["Wave", "Ocean", "Board", "Ride", "Beach"] },
  { word: "Olympics", tabooWords: ["Gold", "Medal", "Sport", "Country", "Games"] },
  { word: "Cycling", tabooWords: ["Bike", "Pedal", "Road", "Helmet", "Tour"] },
  { word: "Archery", tabooWords: ["Bow", "Arrow", "Target", "Aim", "Quiver"] },
  { word: "Skiing", tabooWords: ["Snow", "Mountain", "Slope", "Lift", "Cold"] },
  { word: "Rock Climbing", tabooWords: ["Wall", "Rope", "Grip", "Summit", "Climb"] },

  // ── Places & Travel ─────────────────────────────────────────────────────────
  { word: "Paris", tabooWords: ["France", "Tower", "Art", "Romance", "Fashion"] },
  { word: "New York City", tabooWords: ["Manhattan", "Tall", "Times", "Apple", "City"] },
  { word: "Japan", tabooWords: ["Tokyo", "Sushi", "Cherry", "Anime", "Polite"] },
  { word: "Australia", tabooWords: ["Kangaroo", "Outback", "Reef", "Desert", "Down"] },
  { word: "Egypt", tabooWords: ["Pyramid", "Desert", "Pharaoh", "River", "Ancient"] },
  { word: "Hawaii", tabooWords: ["Beach", "Volcano", "Palm", "Surf", "Paradise"] },
  { word: "London", tabooWords: ["England", "Queen", "Rain", "Bridge", "Red"] },
  { word: "Brazil", tabooWords: ["Carnival", "Soccer", "Amazon", "Dance", "Green"] },
  { word: "Disney World", tabooWords: ["Theme", "Orlando", "Castle", "Ride", "Magic"] },
  { word: "Las Vegas", tabooWords: ["Casino", "Gamble", "Neon", "Hotel", "Show"] },
  { word: "Antarctica", tabooWords: ["Ice", "Penguin", "Pole", "Cold", "Explore"] },
  { word: "Grand Canyon", tabooWords: ["Rock", "Arizona", "Cliff", "View", "Wide"] },
  { word: "Mount Everest", tabooWords: ["Climb", "Summit", "Nepal", "Peak", "Snow"] },
  { word: "Hollywood", tabooWords: ["Movie", "Celebrity", "Star", "Fame", "California"] },
  { word: "Rome", tabooWords: ["Italy", "Ancient", "Colosseum", "Pope", "Pizza"] },
  { word: "Airport", tabooWords: ["Fly", "Terminal", "Luggage", "Gate", "Passport"] },
  { word: "Museum", tabooWords: ["Art", "Exhibit", "Tour", "History", "Gallery"] },
  { word: "Cruise Ship", tabooWords: ["Ocean", "Vacation", "Sail", "Deck", "Port"] },
  { word: "Traffic Jam", tabooWords: ["Car", "Road", "Slow", "Honk", "Wait"] },
  { word: "Camping", tabooWords: ["Tent", "Fire", "Forest", "Sleep", "Nature"] },

  // ── Science & Nature ────────────────────────────────────────────────────────
  { word: "Black Hole", tabooWords: ["Space", "Gravity", "Suck", "Dark", "Star"] },
  { word: "DNA", tabooWords: ["Gene", "Spiral", "Biology", "Code", "Cell"] },
  { word: "Earthquake", tabooWords: ["Shake", "Ground", "Crack", "Disaster", "Plate"] },
  { word: "Volcano", tabooWords: ["Lava", "Erupt", "Mountain", "Fire", "Magma"] },
  { word: "Rainbow", tabooWords: ["Color", "Rain", "Arc", "Sun", "Sky"] },
  { word: "Lightning", tabooWords: ["Thunder", "Storm", "Bolt", "Flash", "Electric"] },
  { word: "Gravity", tabooWords: ["Fall", "Newton", "Pull", "Weight", "Planet"] },
  { word: "Photosynthesis", tabooWords: ["Plant", "Sun", "Leaf", "Energy", "Green"] },
  { word: "Dinosaurs", tabooWords: ["Ancient", "Fossil", "Giant", "Extinct", "Jurassic"] },
  { word: "The Moon", tabooWords: ["Night", "Orbit", "Glow", "Space", "Crater"] },
  { word: "Tornado", tabooWords: ["Wind", "Spin", "Funnel", "Storm", "Cloud"] },
  { word: "Coral Reef", tabooWords: ["Ocean", "Fish", "Color", "Dive", "Sea"] },
  { word: "Telescope", tabooWords: ["Star", "Look", "Lens", "Space", "Astronomer"] },
  { word: "Skeleton", tabooWords: ["Bone", "Halloween", "Death", "Body", "X-Ray"] },
  { word: "Allergies", tabooWords: ["Sneeze", "Pollen", "Itch", "Spring", "Reaction"] },
  { word: "Heatwave", tabooWords: ["Hot", "Summer", "Sweat", "Record", "Dry"] },
  { word: "Recycling", tabooWords: ["Green", "Bin", "Reuse", "Earth", "Plastic"] },
  { word: "Thunderstorm", tabooWords: ["Lightning", "Rain", "Thunder", "Loud", "Wind"] },
  { word: "Clone", tabooWords: ["Copy", "Science", "Identical", "Lab", "Sheep"] },
  { word: "Blizzard", tabooWords: ["Snow", "Cold", "Winter", "Storm", "Ice"] },

  // ── Pop Culture & Entertainment ─────────────────────────────────────────────
  { word: "Beyoncé", tabooWords: ["Queen", "Singer", "Power", "Formation", "Destiny"] },
  { word: "Taylor Swift", tabooWords: ["Singer", "Pop", "Eras", "Heartbreak", "Song"] },
  { word: "Elon Musk", tabooWords: ["Tesla", "SpaceX", "Mars", "Tweet", "Rich"] },
  { word: "Minecraft", tabooWords: ["Block", "Build", "Craft", "Steve", "Dig"] },
  { word: "Fortnite", tabooWords: ["Battle", "Island", "Skin", "Squad", "Drop"] },
  { word: "Super Mario", tabooWords: ["Mushroom", "Jump", "Nintendo", "Bowser", "Coin"] },
  { word: "Karaoke", tabooWords: ["Sing", "Bar", "Microphone", "Song", "Stage"] },
  { word: "Roller Coaster", tabooWords: ["Ride", "Drop", "Scream", "Track", "Theme"] },
  { word: "Halloween", tabooWords: ["Costume", "Trick", "Pumpkin", "Ghost", "October"] },
  { word: "Christmas", tabooWords: ["Tree", "Santa", "Gift", "December", "Snow"] },
  { word: "New Year's Eve", tabooWords: ["Firework", "Midnight", "Toast", "Ball", "January"] },
  { word: "Valentine's Day", tabooWords: ["Love", "Heart", "Flower", "Chocolate", "February"] },
  { word: "Thanksgiving", tabooWords: ["Turkey", "Family", "Grateful", "November", "Feast"] },
  { word: "Wedding", tabooWords: ["Ring", "White", "Vow", "Bride", "Celebrate"] },
  { word: "Monopoly", tabooWords: ["Board", "Money", "Property", "Bank", "Game"] },
  { word: "Magic Trick", tabooWords: ["Illusion", "Wand", "Rabbit", "Disappear", "Card"] },
  { word: "Circus", tabooWords: ["Tent", "Clown", "Tiger", "Tightrope", "Perform"] },
  { word: "Comic Book", tabooWords: ["Hero", "Story", "Panel", "Print", "Marvel"] },
  { word: "Crossword", tabooWords: ["Clue", "Letter", "Box", "Word", "Fill"] },
  { word: "Reality TV", tabooWords: ["Show", "Camera", "Famous", "Drama", "Vote"] },

  // ── Everyday Life & Objects ─────────────────────────────────────────────────
  { word: "Alarm Clock", tabooWords: ["Ring", "Morning", "Wake", "Sleep", "Snooze"] },
  { word: "Umbrella", tabooWords: ["Rain", "Open", "Handle", "Wet", "Storm"] },
  { word: "Mirror", tabooWords: ["Reflect", "Face", "Glass", "Look", "Silver"] },
  { word: "Wallet", tabooWords: ["Money", "Card", "Leather", "Pocket", "Slim"] },
  { word: "Key", tabooWords: ["Lock", "Door", "Ring", "Open", "Metal"] },
  { word: "Glasses", tabooWords: ["See", "Lens", "Nose", "Frame", "Eye"] },
  { word: "Toothbrush", tabooWords: ["Clean", "Teeth", "Morning", "Mint", "Brush"] },
  { word: "Soap", tabooWords: ["Wash", "Lather", "Clean", "Bubble", "Bar"] },
  { word: "Pillow", tabooWords: ["Sleep", "Soft", "Dream", "Bed", "Head"] },
  { word: "Blanket", tabooWords: ["Warm", "Wrap", "Bed", "Cozy", "Cover"] },
  { word: "Remote Control", tabooWords: ["Click", "Channel", "Battery", "TV", "Couch"] },
  { word: "Sunscreen", tabooWords: ["Sun", "SPF", "Beach", "Protect", "Lotion"] },
  { word: "Candle", tabooWords: ["Flame", "Wax", "Light", "Smell", "Blow"] },
  { word: "Backpack", tabooWords: ["School", "Strap", "Carry", "Zipper", "Book"] },
  { word: "Scissors", tabooWords: ["Cut", "Paper", "Sharp", "Blade", "Point"] },
  { word: "Flashlight", tabooWords: ["Dark", "Beam", "Battery", "Shine", "Hand"] },
  { word: "Calendar", tabooWords: ["Month", "Date", "Plan", "Year", "Mark"] },
  { word: "Thermometer", tabooWords: ["Temperature", "Fever", "Mercury", "Sick", "Check"] },
  { word: "Elevator", tabooWords: ["Floor", "Button", "Up", "Door", "Building"] },
  { word: "Vending Machine", tabooWords: ["Snack", "Coin", "Button", "Drink", "Dispense"] },
  { word: "Suitcase", tabooWords: ["Travel", "Pack", "Wheel", "Airport", "Carry"] },
  { word: "Ladder", tabooWords: ["Climb", "Step", "Height", "Rung", "Reach"] },
  { word: "Microwave", tabooWords: ["Heat", "Beep", "Food", "Minutes", "Radiation"] },
  { word: "Fire Extinguisher", tabooWords: ["Spray", "Red", "Emergency", "Foam", "Safety"] },
  { word: "Map", tabooWords: ["Navigate", "Paper", "Direction", "Route", "Legend"] },

  // ── Animals ─────────────────────────────────────────────────────────────────
  { word: "Penguin", tabooWords: ["Cold", "Bird", "Black", "Swim", "Antarctica"] },
  { word: "Elephant", tabooWords: ["Big", "Trunk", "Memory", "Africa", "Tusk"] },
  { word: "Panda", tabooWords: ["China", "Black", "White", "Bamboo", "Bear"] },
  { word: "Dolphin", tabooWords: ["Smart", "Ocean", "Swim", "Jump", "Echolocation"] },
  { word: "Cheetah", tabooWords: ["Fast", "Spot", "Africa", "Run", "Cat"] },
  { word: "Gorilla", tabooWords: ["Primate", "Strong", "Jungle", "Africa", "Chest"] },
  { word: "Flamingo", tabooWords: ["Pink", "Stand", "Bird", "Lake", "Long"] },
  { word: "Octopus", tabooWords: ["Eight", "Ocean", "Ink", "Tentacle", "Smart"] },
  { word: "Shark", tabooWords: ["Bite", "Ocean", "Fin", "Jaw", "Predator"] },
  { word: "Butterfly", tabooWords: ["Wing", "Fly", "Cocoon", "Color", "Garden"] },
  { word: "Koala", tabooWords: ["Australia", "Tree", "Sleepy", "Eucalyptus", "Bear"] },
  { word: "Wolf", tabooWords: ["Howl", "Pack", "Forest", "Wild", "Dog"] },
  { word: "Peacock", tabooWords: ["Feather", "Color", "India", "Bird", "Display"] },
  { word: "Sloth", tabooWords: ["Slow", "Tree", "Hang", "Jungle", "Lazy"] },
  { word: "Eagle", tabooWords: ["Fly", "America", "Bird", "Claw", "Bald"] },

  // ── Concepts & Actions ───────────────────────────────────────────────────────
  { word: "Nap", tabooWords: ["Sleep", "Day", "Short", "Couch", "Rest"] },
  { word: "Procrastination", tabooWords: ["Delay", "Late", "Task", "Avoid", "Tomorrow"] },
  { word: "Meditation", tabooWords: ["Breathe", "Calm", "Mind", "Quiet", "Peace"] },
  { word: "Gossip", tabooWords: ["Rumor", "Talk", "Secret", "Whisper", "Drama"] },
  { word: "Jealousy", tabooWords: ["Green", "Envy", "Want", "Bitter", "Emotion"] },
  { word: "Embarrassment", tabooWords: ["Red", "Face", "Awkward", "Shame", "Cringe"] },
  { word: "Cliffhanger", tabooWords: ["End", "Suspense", "TV", "Dramatic", "Tense"] },
  { word: "First Impression", tabooWords: ["Meet", "Initial", "Judge", "Face", "Opinion"] },
  { word: "Multitasking", tabooWords: ["Several", "Task", "Same", "Juggle", "Busy"] },
  { word: "Binge Watching", tabooWords: ["Eat", "Watch", "Too Much", "Overdo", "Series"] },
  { word: "Laughter", tabooWords: ["Joke", "Sound", "Happy", "Funny", "Smile"] },
  { word: "Sunrise", tabooWords: ["Morning", "Sky", "Orange", "East", "Light"] },
  { word: "Fireworks", tabooWords: ["Boom", "Color", "Celebrate", "Sky", "July"] },
  { word: "DIY Project", tabooWords: ["Build", "Home", "Tool", "Fix", "Make"] },
  { word: "Commute", tabooWords: ["Work", "Train", "Drive", "Daily", "Rush"] },
];
