import type { ImpostorCategory } from "./types";

export interface ImpostorWord {
  word: string;
  hint: string;
}

export const WORD_LISTS: Record<ImpostorCategory, ImpostorWord[]> = {
  Animals: [
    { word: "Elephant", hint: "Land animal" },
    { word: "Penguin", hint: "Land animal" },
    { word: "Octopus", hint: "Sea creature" },
    { word: "Kangaroo", hint: "Land animal" },
    { word: "Giraffe", hint: "Land animal" },
    { word: "Dolphin", hint: "Sea creature" },
    { word: "Cheetah", hint: "Land animal" },
    { word: "Gorilla", hint: "Land animal" },
    { word: "Flamingo", hint: "Land animal" },
    { word: "Chameleon", hint: "Land animal" },
    { word: "Platypus", hint: "Land animal" },
    { word: "Porcupine", hint: "Land animal" },
    { word: "Meerkat", hint: "Land animal" },
    { word: "Narwhal", hint: "Sea creature" },
    { word: "Capybara", hint: "Land animal" },
    { word: "Komodo Dragon", hint: "Land animal" },
    { word: "Sloth", hint: "Land animal" },
    { word: "Crocodile", hint: "Land animal" },
    { word: "Parrot", hint: "Land animal" },
    { word: "Hamster", hint: "Land animal" },
  ],
  "Movies & TV": [
    { word: "Titanic", hint: "Drama" },
    { word: "Friends", hint: "Comedy" },
    { word: "The Office", hint: "Comedy" },
    { word: "Star Wars", hint: "Sci-fi" },
    { word: "Breaking Bad", hint: "Drama" },
    { word: "Avatar", hint: "Sci-fi" },
    { word: "The Lion King", hint: "Animation" },
    { word: "Jurassic Park", hint: "Thriller" },
    { word: "Game of Thrones", hint: "Drama" },
    { word: "Interstellar", hint: "Sci-fi" },
    { word: "Stranger Things", hint: "Thriller" },
    { word: "Inception", hint: "Thriller" },
    { word: "The Dark Knight", hint: "Action" },
    { word: "Pulp Fiction", hint: "Thriller" },
    { word: "Avengers", hint: "Action" },
    { word: "Parasite", hint: "Thriller" },
    { word: "La La Land", hint: "Drama" },
    { word: "Forrest Gump", hint: "Drama" },
    { word: "The Godfather", hint: "Drama" },
    { word: "Shrek", hint: "Animation" },
  ],
  "Food & Drink": [
    { word: "Pizza", hint: "Food" },
    { word: "Sushi", hint: "Food" },
    { word: "Pancakes", hint: "Food" },
    { word: "Lemonade", hint: "Drink" },
    { word: "Tacos", hint: "Food" },
    { word: "Ramen", hint: "Food" },
    { word: "Croissant", hint: "Food" },
    { word: "Guacamole", hint: "Food" },
    { word: "Lasagna", hint: "Food" },
    { word: "Dumplings", hint: "Food" },
    { word: "Nachos", hint: "Food" },
    { word: "Fondue", hint: "Food" },
    { word: "Boba Tea", hint: "Drink" },
    { word: "Cheesecake", hint: "Food" },
    { word: "Pretzels", hint: "Food" },
    { word: "Tiramisu", hint: "Food" },
    { word: "Hot Dog", hint: "Food" },
    { word: "Falafel", hint: "Food" },
    { word: "Burger", hint: "Food" },
    { word: "Donut", hint: "Food" },
  ],
  Sports: [
    { word: "Soccer", hint: "Team sport" },
    { word: "Basketball", hint: "Team sport" },
    { word: "Tennis", hint: "Solo sport" },
    { word: "Surfing", hint: "Solo sport" },
    { word: "Bowling", hint: "Solo sport" },
    { word: "Volleyball", hint: "Team sport" },
    { word: "Gymnastics", hint: "Solo sport" },
    { word: "Fencing", hint: "Solo sport" },
    { word: "Table Tennis", hint: "Solo sport" },
    { word: "Archery", hint: "Solo sport" },
    { word: "Snowboarding", hint: "Solo sport" },
    { word: "Badminton", hint: "Solo sport" },
    { word: "Wrestling", hint: "Solo sport" },
    { word: "Rock Climbing", hint: "Solo sport" },
    { word: "Lacrosse", hint: "Team sport" },
    { word: "Golf", hint: "Solo sport" },
    { word: "Boxing", hint: "Solo sport" },
    { word: "Rugby", hint: "Team sport" },
    { word: "Curling", hint: "Team sport" },
    { word: "Bobsled", hint: "Team sport" },
  ],
  "Famous Places": [
    { word: "Eiffel Tower", hint: "Man-made landmark" },
    { word: "Grand Canyon", hint: "Natural landmark" },
    { word: "Times Square", hint: "Man-made landmark" },
    { word: "Great Wall of China", hint: "Man-made landmark" },
    { word: "Machu Picchu", hint: "Man-made landmark" },
    { word: "Colosseum", hint: "Man-made landmark" },
    { word: "Niagara Falls", hint: "Natural landmark" },
    { word: "Sydney Opera House", hint: "Man-made landmark" },
    { word: "Stonehenge", hint: "Man-made landmark" },
    { word: "Sahara Desert", hint: "Natural landmark" },
    { word: "Amazon Rainforest", hint: "Natural landmark" },
    { word: "Mount Everest", hint: "Natural landmark" },
    { word: "Statue of Liberty", hint: "Man-made landmark" },
    { word: "Big Ben", hint: "Man-made landmark" },
    { word: "Taj Mahal", hint: "Man-made landmark" },
    { word: "Angkor Wat", hint: "Man-made landmark" },
    { word: "Northern Lights", hint: "Natural landmark" },
    { word: "Santorini", hint: "Man-made landmark" },
    { word: "Petra", hint: "Man-made landmark" },
    { word: "Easter Island", hint: "Man-made landmark" },
  ],
  "Jobs & Professions": [
    { word: "Firefighter", hint: "Outdoors" },
    { word: "Dentist", hint: "Indoors" },
    { word: "Chef", hint: "Indoors" },
    { word: "Pilot", hint: "Outdoors" },
    { word: "Teacher", hint: "Indoors" },
    { word: "Astronaut", hint: "Outdoors" },
    { word: "Architect", hint: "Indoors" },
    { word: "Surgeon", hint: "Indoors" },
    { word: "Judge", hint: "Indoors" },
    { word: "Archaeologist", hint: "Outdoors" },
    { word: "Marine Biologist", hint: "Outdoors" },
    { word: "Air Traffic Controller", hint: "Indoors" },
    { word: "Vet", hint: "Indoors" },
    { word: "Puppeteer", hint: "Indoors" },
    { word: "Bomb Disposal", hint: "Outdoors" },
    { word: "Accountant", hint: "Indoors" },
    { word: "Journalist", hint: "Outdoors" },
    { word: "Programmer", hint: "Indoors" },
    { word: "Electrician", hint: "Indoors" },
    { word: "Plumber", hint: "Indoors" },
  ],
  "Everyday Objects": [
    { word: "Umbrella", hint: "Common household item" },
    { word: "Toothbrush", hint: "Common household item" },
    { word: "Backpack", hint: "Common household item" },
    { word: "Stapler", hint: "Tool" },
    { word: "Flashlight", hint: "Tool" },
    { word: "Scissors", hint: "Tool" },
    { word: "Rubber Duck", hint: "Common household item" },
    { word: "Duct Tape", hint: "Tool" },
    { word: "Whisk", hint: "Tool" },
    { word: "Compass", hint: "Tool" },
    { word: "Bubble Wrap", hint: "Common household item" },
    { word: "Paper Clip", hint: "Common household item" },
    { word: "Thermometer", hint: "Tool" },
    { word: "Magnifying Glass", hint: "Tool" },
    { word: "Tape Measure", hint: "Tool" },
    { word: "Sticky Notes", hint: "Common household item" },
    { word: "Lint Roller", hint: "Common household item" },
    { word: "Corkscrew", hint: "Tool" },
    { word: "Padlock", hint: "Common household item" },
    { word: "Doorstop", hint: "Common household item" },
  ],
};

export const CATEGORIES = Object.keys(WORD_LISTS) as ImpostorCategory[];

export function getRandomWord(category: ImpostorCategory): ImpostorWord {
  const list = WORD_LISTS[category];
  return list[Math.floor(Math.random() * list.length)];
}
